data_directory: /home/mhturner/Dropbox/ClandininLab/SegmentationData
flystim_data_directory: /home/mhturner/Dropbox/ClandininLab/SegmentationData
igor_directory: /home/mhturner/Dropbox/ClandininLab/Analysis/Igor
