data_directory: /Users/mhturner/Dropbox/ClandininLab/CurrentData
flystim_data_directory: /Users/mhturner/Dropbox/ClandininLab/CurrentData/FlystimData
igor_directory: /Users/mhturner/Dropbox/ClandininLab/Analysis/Igor
