data_directory: /Users/mhturner/Dropbox/ClandininLab/CurrentData
flystim_data_directory: /Users/mhturner/Dropbox/ClandininLab/CurrentData/FlystimData
igor_directory: /Users/mhturner/Dropbox/ClandininLab/Analysis/Igor


analysis_settings:
  AODscope:
    rig: AODscope
    roi_names: ['Lobula plate', 'lo1', 'Med']

  Bruker:
    rig: Bruker
    roi_names: ['single_dendrite', 'axon', 'mult_dendrite']