data_directory: /home/mhturner/Dropbox/ClandininLab/CurrentData
flystim_data_directory: /home/mhturner/Dropbox/ClandininLab/CurrentData/FlystimData
igor_directory: /home/mhturner/Dropbox/ClandininLab/Analysis/Igor
